spring:
  application:
    name: external-gateway
  profiles:
    active: local

server:
  port: 8070

logging:
  slack:
    enabled: false
    webhook-url:
    channel: dev
  level:
    root: info
    lozm: debug
    org.springframework:
      web.filter.CommonsRequestLoggingFilter: debug
      cloud.loadbalancer.config.BlockingLoadBalancerClientAutoConfiguration: error
      boot.actuate: error
    com.netflix:
      config.sources.URLConfigurationSource: error
      discovery: error

eureka:
  client:
    enabled: false
  instance:
    prefer-ip-address: true

management:
  endpoints.web.exposure.include: "*"
  endpoint.health.show-details: ALWAYS

zuul:
  igoredServices: '*'
  routes:
    sample-api:
      path: /sample-api/**
      serviceId: sample-api
  retryable: true
  ribbon-isolation-strategy: THREAD
  thread-pool:
    use-separate-thread-pools: true
    thread-pool-key-prefix: zuul-

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 120000

ribbon:
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false
  ReadTimeout: 5000
  ConnectTimeout: 1000
  MaxTotalConnections: 300
  MaxConnectionsPerHost: 100
  retryableStatusCodes: 500
